version: '3.9'

services:
  db:
    build: 
      dockerfile: Dockerfile-mariadb
    container_name: mariadb_hyp3
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: hyp3db
      MYSQL_USER: hyp3
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
      LANG: C.UTF-8
    ports:
      - "6033:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  php-apache:
    build: 
      dockerfile: Dockerfile-php
    container_name: hyp3
    volumes:
      - ./webapp:/var/www/html
    ports:
      - "8080:80"
      - "7443:443"
    environment:
      DB_HOST: db:3306
      DB_USER: hyp3
      DB_NAME: hyp3db
      DB_PASSWORD: secret
    restart: always
  phpmyadmin:
    build:
      dockerfile: Dockerfile-phpmyadmin
    container_name: pma_hyp3
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: hyp3
      PMA_PASSWORD: secret
    restart: always
    ports:
      - 8082:80
      - 8443:443
volumes:
  dbdata:
networks:
  default:
    name: webnet_hyp3
