# Linux x64 and MAC Intel and MAC M1
FROM phpmyadmin

LABEL maintainer="rimbert.rudisch-sommer@fh-hagenberg.at"

COPY src /src
# Install scripts
RUN    cd /src \
    && chmod 755 *.sh \
    && /src/install-apt.sh \
    && /src/basic_tools.sh \
    && /src/switchhttps.sh
    