version: '3.9'

services:
  php-apache:
    build: 
      dockerfile: Dockerfile-php
    container_name: hyp3
    volumes:
      - ./webapp:/var/www/html
    ports:
      - "8080:80"
volumes:
  dbdata:
networks:
  default:
    name: webnet_hyp3
